name: Lint & Link PR with Notion
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
concurrency: # NOTE: 複数のPRでWorkflowが同時に実行されないように設定する必要がある
  group: ${{ github.workflow }}
  cancel-in-progress: false
env:
  TZ: "Asia/Tokyo"

jobs:
  lint-pr-with-notion:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Lint PR Title
        id: lint-pr-title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            refactor
            chore
            ci
            perf
            docs
            style
            test
            revert
          subjectPattern: .+\s\(#\w+-\d+\)\s?$ # check if linked with Notion Task
